### ISSUE TITLE
Customize the script to run for dependent packages

### ISSUE THREAD

**Issue by egoist** [egoist/tasco#2]
By default it just runs the same script, I'm introducing a tasco.toml for this:

```toml
[scripts.dev]
dependOn = [ "build", "dev" ]

[scripts."my-app#dev"]
dependOn = [ "my-data#build-data" ]
```
